# Generated by Django 3.2.6 on 2022-08-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.URLField(max_length=255),
        ),
    ]
